services:
  api:
    build: .
    image: yt-dlp-api
    container_name: yt-dlp-api
    environment:
      REDIS_ADDR: "redis:6379"
    env_file: .env
    ports:
      - "${SERVER_PORT}:8080"
    restart: unless-stopped
