services:
  api:
    build: .
    image: urlasso-api
    container_name: urlasso-api
    env_file: .env
    networks:
      - urlasso-api_net
      - data_net
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    restart: unless-stopped

networks:
  urlasso-api_net:
    name: urlasso-api_net
  data_net:
    external: true